"""schema_update_task4

Revision ID: 4f3316c4dc5b
Revises: c699da89ea3a
Create Date: 2026-03-20 19:04:33.938233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3316c4dc5b'
down_revision: Union[str, Sequence[str], None] = 'c699da89ea3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Handle Enums for PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        # Update languagesupport (handling existing Enum)
        new_languages = ['RO', 'PL', 'TR', 'RU', 'EN', 'BG', 'SR', 'OTHER']
        for lang in new_languages:
            op.execute(sa.text(f"ALTER TYPE languagesupport ADD VALUE IF NOT EXISTS '{lang}'"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('contract_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    op.create_table('monthly_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_adjustments_id'), 'monthly_adjustments', ['id'], unique=False)
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=False, server_default='OVERTIME'))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_hours_week', sa.Integer(), nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Enum('DE', 'UK', 'RO', 'PL', 'TR', 'RU', 'EN', 'BG', 'SR', 'OTHER', name='languagesupport'),
               existing_nullable=True)
        batch_op.drop_column('contract_hours_month')
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_hours_month', sa.FLOAT(), nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.Enum('DE', 'UK', 'RO', 'PL', 'TR', 'RU', 'EN', 'BG', 'SR', 'OTHER', name='languagesupport'),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.drop_column('contract_hours_week')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_type')
    op.drop_index(op.f('ix_monthly_adjustments_id'), table_name='monthly_adjustments')
    op.drop_table('monthly_adjustments')
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
