"""Add company contact info and site description

Revision ID: c699da89ea3a
Revises: 7325dad472f8
Create Date: 2026-03-17 21:02:36.492469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c699da89ea3a'
down_revision: Union[str, Sequence[str], None] = '7325dad472f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'description')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'phone')
    # ### end Alembic commands ###
