"""Add GPS to TimeEvents

Revision ID: e55c1f034990
Revises: ab97bc167e2c
Create Date: 2026-03-15 18:19:18.524789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55c1f034990'
down_revision: Union[str, Sequence[str], None] = 'ab97bc167e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_events', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('time_events', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('time_events', sa.Column('gps_accuracy_m', sa.Float(), nullable=True))
    op.add_column('time_events', sa.Column('is_suspicious', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_events', 'is_suspicious')
    op.drop_column('time_events', 'gps_accuracy_m')
    op.drop_column('time_events', 'lon')
    op.drop_column('time_events', 'lat')
    # ### end Alembic commands ###
